import {Mine,CAPACITY,VALUE} from './engine.js';
import {Renderer,ASSETS,PARTS} from './renderer.js';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const model=new Mine(),canvas=$('#mine');let renderer,paused=false,speed=1,previous=0,lastUI=0,hidden=false;
const images={};
for(let i=0;i<CAPACITY;i++)$('#slots').append(document.createElement('span'));
const messages={idle:'Esperando mineral en la cinta',approach:'La pinza se acerca al mineral',grab:'Sujetando una piedra',lift:'Levantando el mineral',carry:'Transportando hacia el vagón',lower:'Colocando la piedra en el vagón',release:'Carga depositada',return:'El brazo vuelve a la cinta'};
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));renderer?.draw(model);}
function ui(){const moving=model.cart!=='parked';$('#cargo').textContent=model.cargo.length;$('#coins').textContent=model.coins.toLocaleString('es');$('#clock').textContent=`${String(Math.floor(model.time/60)).padStart(2,'0')}:${String(Math.floor(model.time%60)).padStart(2,'0')}`;$('#fill-percent').textContent=`${Math.round(model.cargo.length/CAPACITY*100)}%`;$('#slots').querySelectorAll('span').forEach((s,i)=>s.classList.toggle('filled',i<model.cargo.length));$('#collect').disabled=moving||(!model.cargo.length&&!model.holding)||model.collectRequested;$('#collect-value').textContent=`+${(model.cargo.length+(model.holding?1:0))*VALUE} ◈`;$('#collect').firstElementChild.textContent=model.collectRequested?'Salida preparada':moving?'Vagón en ruta':'Enviar vagón';$('#cart-status').textContent=model.cart==='outbound'?'Entregando el mineral':model.cart==='returning'?'Regresando vacío':model.collectRequested?'Sale al terminar esta carga':'Estacionado en carga';$('#phase-label').textContent=paused?'Animación en pausa':moving?model.cart==='outbound'?'El vagón lleva el mineral al almacén':'El vagón regresa a la mina':messages[model.phase];$('#running-label').textContent=paused?'EN PAUSA':'EN MARCHA';$('#pause-icon').textContent=paused?'▶':'Ⅱ';$('#pause').setAttribute('aria-label',paused?'Reanudar animación':'Pausar animación');all('[data-step]').forEach(e=>e.classList.toggle('active',!paused&&(e.dataset.step==='drill'||e.dataset.step==='belt'||(e.dataset.step==='arm'&&model.phase!=='idle')||(e.dataset.step==='cart'&&moving))));}
function frame(ts){const dt=previous?Math.min((ts-previous)/1000,.1):0;previous=ts;if(!paused&&!hidden)model.update(dt*speed);renderer.draw(model);if(ts-lastUI>80){ui();lastUI=ts;}requestAnimationFrame(frame);}
$('#pause').onclick=()=>{paused=!paused;ui();};$('#reset').onclick=()=>{model.reset();ui();renderer?.draw(model);};$('#collect').onclick=()=>{model.collect();ui();};
all('[data-speed]').forEach(b=>b.onclick=()=>{speed=Number(b.dataset.speed);all('[data-speed]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
all('[data-view]').forEach(b=>b.onclick=()=>{renderer?.setView(b.dataset.view);$('.scene-panel').classList.toggle('map',b.dataset.view==='map');all('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));resize();});
$('#assets-open').onclick=()=>$('#assets-dialog').showModal();$('#assets-close').onclick=()=>$('#assets-dialog').close();$('#assets-dialog').onclick=e=>{if(e.target===$('#assets-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
document.addEventListener('visibilitychange',()=>{hidden=document.hidden;previous=0;});new ResizeObserver(resize).observe(canvas.parentElement);
function gallery(){const list=[['Fondo fijo','background',null],...Array.from({length:6},(_,i)=>[`Taladro · fotograma ${i+1}`,'drill',[Math.floor(i%3)*512,Math.floor(i/3)*512+175,512,240]]),['Brazo superior','parts',PARTS.upper],['Antebrazo','parts',PARTS.fore],['Soporte de la pinza','parts',PARTS.palm],['Dedo de pinza × 2','parts',PARTS.jaw],['Superficie de la cinta','parts',PARTS.belt],['Piedra de oro','parts',PARTS.ore],['Vagón vacío','parts',PARTS.wagon]];for(const [name,key,rect] of list){const tile=document.createElement('div');tile.className='asset-tile';const c=document.createElement('canvas');c.width=360;c.height=180;const ctx=c.getContext('2d'),im=images[key],r=rect||[0,0,im.width,im.height];const scale=Math.min(320/r[2],154/r[3]);ctx.drawImage(im,...r,(360-r[2]*scale)/2,(180-r[3]*scale)/2,r[2]*scale,r[3]*scale);const p=document.createElement('p');p.textContent=name;tile.append(c,p);$('#asset-grid').append(tile);}}
try{await Promise.all(Object.entries(ASSETS).map(async([key,src])=>{const im=new Image();im.src=new URL(src,import.meta.url).href;await im.decode();images[key]=im;}));renderer=new Renderer(canvas,images);gallery();resize();ui();$('#loading').hidden=true;document.body.dataset.ready='true';requestAnimationFrame(frame);
 // Read-only state plus explicit stepping lets the independent preview be tested deterministically.
 window.minePreview={snapshot:()=>({...model.snapshot(),paused,speed,view:renderer.view}),pause:()=>{paused=true;ui();},step:seconds=>{if(!paused)throw Error('Pause before stepping');model.update(seconds);renderer.draw(model);ui();},reset:()=>{model.reset();renderer.draw(model);ui();}};
}catch(error){console.error(error);$('#loading').hidden=true;$('#error').hidden=false;}
